[logger]
level = "INFO"
type = "FILE"
directory = "logs"

[storage]
type = "DB"
user = "calendar"
pass = "1231"
port = 5431
host = "127.0.0.1"
name = "calendar"

[http]
host = "127.0.0.1"
port = "8081"

[grpc]
host = "127.0.0.1"
port = "50051"
